In [ ]:
#数据的导入
import pandas as pd
df = pd.read_csv('data/employees.csv')


#数据的导出
df.to_csv('data/new.csv')

In [ ]:
#JSON 
df = pd.read_json('data/data1.json')


import json
with open('data/test.json') as f:
    data = json.load(f)
print(type(data))
df = pd.DataFrame(data["users"])
print(type(df))
df

In [ ]:
# 缺失值的处理
import numpy as np
import pandas as pd
s = pd.Series([1,2,np.nan,None,pd.NA])
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[None,4,6]])
print(s)
print(df)
#检查是否是缺失值
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())

In [ ]:
print(df.isna())
print(df.isnull())
print(df.isna().sum(axis = 1))  
print(df.isnull())

In [ ]:
#剔除缺失值
print(s.dropna())
print(df)
print(df.dropna())  #剔除一整条数据
print(df.dropna(how = "all"))   #只有所有都是缺失值，才删除
print(df.dropna(thresh = 2))    #至少有n个不是缺失值，就保留

In [ ]:
import pandas as pd
#填充缺失值
df  = pd.read_csv('data/weather_withna.csv')
df.isna().sum(axis = 0)
print(df.fillna({'temp_max':20,'wind':2.5}))    #使用字典来填充

print(df.fillna(df[['temp_max','wind']].mean()).tail()) #用统计值来填充
print(df.ffill().tail())    #用前面的值来填充
print(df.bfill().tail())    #用后面的值来填充

In [ ]:
# 检测数据重复

In [2]:
# 数据类型的转换
import pandas as pd
import numpy as np
df = pd.read_csv('data/sleep.csv')
df.dtypes
df['age'] = df['age'].astype('int16')
df['gender'] = df['gender'].astype('category')

In [ ]:
# 数据转换
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}

df = pd.DataFrame(data)
print(df)
df.T    #行列转置
'''
1 Alice math 90
1 Alice english 88
1 Alice science 95
'''

#宽表转化成长表
df2 = pd.melt(df, id_vars=['ID','name'],var_name='科目',value_name='分数')
print(df2.sort_values('name'))

#长表转宽表
df3 = pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')
print(df3)

In [5]:
# 数据转换
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}

df = pd.DataFrame(data)
print(df)

#分列
df[['first','last']] = df['name'].str.split(" ",expand=True)
df

   ID         name  Math  English  Science
0   1  alice smith    90       88       95
1   2    bob smith    85       92       89

   ID         name  Math  English  Science  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith

In [ ]:
#数据分箱   pd.cut(x,bins,labels)

import pandas as pd
df = pd.read_csv('data/employees.csv')
df1 = df.head(10).copy()
#print(df1)
pd.cut(df1['salary'],bins=2)    #bins = n，表示分成n段区间 , 起始值和结束值是数据最小值和最大值
pd.cut(df1['salary'],bins=2).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000])    #bins = list,分成n段区间
df1['收入范围'] = pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])

pd.qcut(df1['salary'],3).value_counts() #等频率

#字符串 --> 类别 --> 统计
#数值 --> 分箱 --> 统计

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

In [24]:
#df.rename() df.set_index() df.reset_index()
data  = {
    'name':['jack','alice','tom','bob'],
    'age':[20,30,30,40],
    'gender':['Female','male','Female','male']
}
df  = pd.DataFrame(data)
df.set_index("name")
df.reset_index(inplace=True)
df.rename(columns={'age':'年龄'},index={0:4})
df.index = [1,2,3,4]
#df.columns('0','0','0','0')

In [37]:
#时间数据的处理
import pandas as pd
d = pd.Timestamp('2015-05-02 10:22')
print(d)
print(type(d))
print("年", d.year)
print("月", d.month)
print("日", d.day)
print(d.hour, d.minute, d.second)

#方法
print("星期几：", d.day_name())
print("转换为天：", d.to_period("D"))

2015-05-02 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年 2015
月 5
日 2
10 22 0
星期几： Saturday
转换为天： 2015-05-02

In [ ]:
#字符串转换为日期类型
a = pd.to_datetime('2025-10-12 10:15')
print(a)
print(type(a))
print(a.day_name())

df = pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df
print(df.info())
print(type(df['datetime']))
print(df['datetime'].dt.day_name())

2025-10-12 10:15:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
Sunday
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 200.0+ bytes
None
<class 'pandas.core.series.Series'>
0     Sunday
1     Monday
2    Tuesday
Name: datetime, dtype: object

In [58]:
# csv 日期转换
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
# df['datetime'] = pd.to_datetime(df['date'])
# df['datetime'].dt.day_name()

In [61]:
# 日期数据作为索引
print(df)
#df.set_index('date',inplace=True)  #设置原来的df索引
print(df.loc['2013':'2015'])

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]
            precipitation  temp_max  temp_min  wind weather
date
2013-01-01            0.0       5.0      -2.8   2.7     sun
2013-01-02            0.0       6.1      -1.1   3.2     sun
2013-01-03            4.1       6.7      -1.7   3.0    rain
2013-01-04            2.5      10.0       2.2   2.8    rain
2013-01-05            3.0       6.7       4.4   3.1    rain
...                   ...       ...       ...   ...     ...
2015-12-27            8.6       4.4       1.7   2.9    rain
2015-12-28            1.5       5.0       1.7   1.3    rain
2015-12-29            0.0       7.2       0.6   2.6     fog
2015-12-30            0.0       5.6      -1.0   3.4     sun
2015-12-31            0.0       5.6      -2.1   3.5     sun

[1095 rows x 5 columns]

In [63]:
#时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2023-02-26')
d3 = d2 - d1
print(d3)

3694 days 00:00:00

In [65]:
days = pd.date_range('2025-07-03','2026-02-09',freq = "W")
days = pd.date_range('2025-07-03',periods=10,freq = "W")
print(days)

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[ns]', freq='W-SUN')

In [67]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
#重新采样
df.set_index('date',inplace=True)
df[['temp_max','temp_min']].resample("YS").mean()
df[['temp_max','temp_min']].resample("YE").mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [13]:
#分组聚合
# df.groupby('分组的子段')['聚合的字段'].聚合函数()
import pandas as pd
df = pd.read_csv('data/employees.csv')
print(df['department_id'].isna().sum())     #检测数据是否有缺失值nan
df = df.dropna(subset=['department_id'])    #清除缺失值
print(df['department_id'].isna().sum())

df['department_id'] = df['department_id'].astype('int64')   #将department_id改为整数
#计算不同部门的平均薪资
df.groupby('department_id').groups          #查看分组
df.groupby('department_id').get_group(20)   #查看具体的某个分组数据

df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)      #round(2)是四舍五入保留两位小数

#计算不同部分不同岗位的人的平均薪资
df2 = df.groupby(['department_id','job_id'])[['salary']].mean()
df2 = df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2.sort_values('salary',ascending=False)

1
0

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
16            100      FI_MGR  12000.0
18            110      AC_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0

# 项目

In [27]:
# 1.导入库
import pandas as pd
import numpy as np

# 2.导入数据
df = pd.read_csv('data/sleep.csv')
# df.head()
# df.info()
# df.describe()   #了解数据的相关内容

# 3.数据清洗
df.isna().sum()
df.drop(columns='sleep_disorder',inplace=True)  #删除sleep_disorder
df.head()

# 4. 数据特征构造
df['gender'] = df['gender'].astype('category')  #将字符串转换为类别
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df[['high','low']] = df['blood_pressure'].str.split('/',expand=True)    #拆分成两列独立的数值列 

#睡眠质量的分箱
labels = ['差','中','优']
df['quality_level'] = pd.cut(df['sleep_quality'],bins= 3,labels=labels)
age_labels = ['青少年','中年','老年']
df['age_level'] = pd.cut(df['age'],bins= 3,labels=age_labels)

# 5. 数据的统计与分析
print(df['bmi_category'].value_counts())

#根据不同的bmi分组，睡眠质量
df.groupby('bmi_category').agg({
    'sleep_duration':'mean',
    'sleep_quality':'mean',
    'stress_level':'mean'
})

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12964\3161823296.py:32: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('bmi_category').agg({

              sleep_duration  sleep_quality  stress_level
bmi_category
Normal              7.794505       6.342857      4.857143
Obese               8.072449       6.189796      5.765306
Overweight          8.274312       6.101835      5.642202
Underweight         7.982353       5.896078      5.558824